/**
 * usePageSeo — one-liner per page to set all SEO meta tags.
 *
 * Sets: title, og:title, description, og:description, og:image,
 * og:url, twitter:card, twitter:title, twitter:description, twitter:image,
 * and canonical link.
 *
 * OG images are generated by a Nitro server route using
 * @cloudflare/pages-plugin-vercel-og (Satori on CF Workers).
 * The URL pattern is: /__og-image__/<template>?title=...&description=...
 */

/** Map component names to template slugs used in the OG image route */
export function usePageSeo(opts: {
  title: string
  description: string
  image?: string
  type?: 'website' | 'article' | 'profile'
  ogImageComponent?: string
  ogImageProps?: Record<string, unknown>
}) {
  const route = useRoute()
  const runtimeConfig = useRuntimeConfig()
  const siteUrl = (runtimeConfig.public.appUrl || 'https://austin-texas.net').replace(/\/$/, '')
  const canonicalUrl = `${siteUrl}${route.path}`

  useSeoMeta({
    title: opts.title,
    ogTitle: opts.title,
    description: opts.description,
    ogDescription: opts.description,
    ogUrl: canonicalUrl,
    ogType: opts.type || 'website',
    twitterCard: 'summary_large_image',
    twitterTitle: opts.title,
    twitterDescription: opts.description,
  })

  if (opts.image) {
    // Explicit static image provided
    useSeoMeta({
      ogImage: opts.image,
      twitterImage: opts.image,
    })
  } else {
    // @ts-expect-error — OG component key (Takumi / OgImageDefaultTakumi) is valid at runtime; nuxt-og-image types can be strict
    defineOgImage(opts.ogImageComponent || 'Takumi', {
      title: opts.title,
      description: opts.description,
      ...(opts.ogImageProps || {}),
    })
  }

  useHead({
    link: [{ rel: 'canonical', href: canonicalUrl }],
  })
}
